### ISSUE TITLE
400: Invalid label name - invalidArgument

### ISSUE THREAD

**Issue by portpatsy** [jay0lee/got-your-back#110] opened 2016-07-28 19:57 UTC
Hi,

I am using the latest version of GYB(v0.47) and currently in the middle of restoring the emails to another email address and I got an error: 400: Invalid label name - invalidArgument and the restore died. 

I tried to run the command again with the --debug > label-failure-output.txt at the end but it gave me another 400: Invalid label name - invalidArgument. 

Please help.

**Comment by portpatsy** [comment] 2016-07-28 21:58
I tried to resume the restore by moving out one of the parent folders which were 2014, 2015 and 2016 respectively.  It resumed the restore but not for long. As it was restoring a large email, it encountered a 409: Label name exists or conflicts - aborted.

**Comment by jay0lee** [comment] 2016-08-21 00:47
Duplicate of #105

**Closed by jay0lee** 2016-08-21 00:47 UTC
