### ISSUE TITLE
--service-account not working - 403 when fetching each individual message id

### ISSUE THREAD

**Issue by sxe7532** [jay0lee/got-your-back#258] opened 2020-03-19 14:59 UTC
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Run gyb --email yourusersemail@yourcompany.com --service-account

Expected outcome (what are you trying to do?):
Backup a google user's email account

Actual outcome (what errors or bad behavior do you see instead?):
Successfully requests a list of message Ids but fails when requesting each message id. 

<HttpError 403 when requesting https://www.googleapis.com/gmail/v1/users/me/messages/1*>

**Comment by hjzweerd** [comment] 2020-03-19 16:50
I am having the same problem I have created a new project and I still have the same issue..
It did work 2 weeks ago,

**Comment by hjzweerd** [comment] 2020-03-19 16:55
Ok, it works only when the account you are trying to backup is not suspended.

**Comment by sxe7532** [comment] 2020-03-19 20:55
You are right! Though it worked on suspended accounts last week. Did something change?

**Comment by HJZWEERS** [comment] 2020-03-20 16:34
I just opened a ticket with Google as transferreing data from a Gsuite account when you delete it is also not working, you will have to enable the account and use the transfer ownership tool on the drive admin for it to work. So looks like an issue on Google's side.

**Comment by mystix** [comment] 2020-03-25 08:37
Facing the same issue -- error when attempting to backup suspended gsuite user accounts.

Seems like google changed something on their end in the past month (I ran into this issue issue early last week).

**Comment by jay0lee** [comment] 2020-03-25 10:24
checking with Google to see if there was a change here but I have no timeline on a response. For now I suggest resetting user's password and locking down the account rather than suspending while GYB backup is occurring.

**Comment by HJZWEERS** [comment] 2020-03-30 10:55
Hi all, this seems to be working again, just did a backup on a suspended account and it didn't come up with any errors.

**Comment by mystix** [comment] 2020-03-30 12:45
> Hi all, this seems to be working again, just did a backup on a suspended account and it didn't come up with any errors.

Just tested on a suspended account as well -- I can confirm backup on a suspended account now works correctly.

**Closed** 2020-07-05 13:29 UTC
Labels: wontfix
